apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: haingyen/backend:b299a4e30700e2f1892a0a3475a65b40a7bd1457
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-service:27017/mydb"
        - name: PORT
          value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001