apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: haingyen/backend:be8aab7f7d985929f160839bfd167300af9c388f
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: todox-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001