name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend image
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

    - name: Build and push frontend image
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

    # Tự động cập nhật file Kubernetes deployment.yaml với image tags mới nhất vừa được build
    - name: Update Kubernetes manifest
      run: |
        # Update image tags trong deployment.yaml
        sed -i 's|image:.*backend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}|' k8s/backend.deployment.yaml
        sed -i 's|image:.*frontend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}|' k8s/frontend.deployment.yaml

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add k8s/*.yaml
        git commit -m "Update images to ${{ github.sha }}"
        git push
  deploy:
    runs-on: ubuntu-latest
    # environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'  
        kubeconfig: ${{ secrets.KUBECONFIG }}  

    - name: Deploy ArgoCD Application
      run: kubectl apply -f argocd/application.yaml
